# Generated by Django 4.2.1 on 2023-05-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservacionTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50, verbose_name='Nombre de Cliente')),
                ('cantidad_persona', models.PositiveIntegerField(verbose_name='Cantidad de Personas')),
                ('lugar', models.CharField(max_length=100, verbose_name='Lugar de Recogida')),
                ('fecha', models.DateField(verbose_name='Fecha de Reservación')),
                ('hora', models.TimeField(verbose_name='Hora de Reservación')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='ReservacionGastronmica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50, verbose_name='Nombre de Cliente')),
                ('cantidad_persona', models.PositiveIntegerField(verbose_name='Cantidad de Personas')),
                ('fecha', models.DateField(verbose_name='Fecha de Reservación')),
                ('hora', models.TimeField(verbose_name='Hora de Reservación')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.entidad')),
            ],
        ),
        migrations.CreateModel(
            name='ReservacionAlojaminto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50, verbose_name='Nombre de Cliente')),
                ('ci', models.PositiveIntegerField(verbose_name='Carnet de Identidada')),
                ('cantidad_persona', models.PositiveIntegerField(verbose_name='Cantidad de Personas')),
                ('fecha', models.DateField(verbose_name='Fecha de Reservación')),
                ('cantidad_dia', models.PositiveIntegerField(verbose_name='Cantidad de Días')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.entidad')),
            ],
        ),
    ]
